# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.BigIntegerField()),
                ('Tz', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('weekday', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('length', models.DecimalField(decimal_places=10, max_digits=13)),
                ('cycles', models.IntegerField()),
                ('deep', models.DecimalField(decimal_places=10, max_digits=13)),
                ('Geo', models.TextField()),
                ('awake_during_the_night', models.IntegerField()),
                ('sleep_data', models.TextField()),
            ],
        ),
    ]
