# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aTimeLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityType', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('file_to_process', models.CharField(max_length=250)),
                ('file_type', models.CharField(max_length=50)),
            ],
        ),
    ]
