# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withingsapp', '0002_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='group',
            field=models.ForeignKey(help_text=b"The measurement's group", on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='withingsapp.MeasureGroup'),
        ),
    ]
