# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('userId', models.TextField()),
                ('humanId', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('tzOffset', models.TextField()),
                ('source', models.TextField()),
                ('unit', models.TextField()),
                ('heartRate', models.TextField()),
                ('systolic', models.TextField()),
                ('diastolic', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HumanAPIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanId', models.IntegerField(help_text='The HumanAPI user ID')),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('public_token', models.TextField(help_text='OAuth access token secret')),
                ('last_update', models.DateTimeField(blank=True, help_text="The datetime the user's HumanAPI data was last updated", null=True)),
                ('user', models.OneToOneField(help_text='The user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
